// <auto-generated />
using System;
using DataAccessLayer.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220311123856_Artwork_tag_id_correction")]
    partial class Artwork_tag_id_correction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityLayer.Concrete.Artwork", b =>
                {
                    b.Property<int>("ArtworkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtworkName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("ArtworkID");

                    b.HasIndex("CollectionID");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ArtworkLayer", b =>
                {
                    b.Property<int>("ArtworkLayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtworkID")
                        .HasColumnType("int");

                    b.Property<int>("CollectionLayerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ArtworkLayerID");

                    b.HasIndex("ArtworkID");

                    b.HasIndex("CollectionLayerID");

                    b.ToTable("ArtworkLayers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ArtworkTag", b =>
                {
                    b.Property<int>("ArtworkTagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtworkID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("ArtworkTagID");

                    b.HasIndex("ArtworkID");

                    b.HasIndex("TagID");

                    b.ToTable("ArtworkTags");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Collection", b =>
                {
                    b.Property<int>("CollectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CollectionName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("CollectionID");

                    b.HasIndex("UserID");

                    b.ToTable("Collections");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CollectionAnalytic", b =>
                {
                    b.Property<int>("CollectionAnalyticID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("CollectionAnalyticID");

                    b.HasIndex("CollectionID");

                    b.ToTable("CollectionAnalytics");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CollectionLayer", b =>
                {
                    b.Property<int>("CollectionLayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<string>("CollectionLayerName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("LayerIndex")
                        .HasColumnType("int");

                    b.Property<int>("LayerTypeID")
                        .HasColumnType("int");

                    b.Property<int>("Popularity")
                        .HasColumnType("int");

                    b.HasKey("CollectionLayerID");

                    b.HasIndex("CollectionID");

                    b.HasIndex("LayerTypeID");

                    b.ToTable("CollectionLayers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.LayerTag", b =>
                {
                    b.Property<int>("LayerTagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CollectionLayerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TagID")
                        .HasColumnType("int");

                    b.HasKey("LayerTagID");

                    b.HasIndex("CollectionLayerID");

                    b.HasIndex("TagID");

                    b.ToTable("LayerTags");
                });

            modelBuilder.Entity("EntityLayer.Concrete.LayerType", b =>
                {
                    b.Property<int>("LayerTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CollectionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LayerTypeName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("LayerTypeID");

                    b.HasIndex("CollectionID");

                    b.ToTable("LayerTypes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Tag", b =>
                {
                    b.Property<int>("TagID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TagName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TagID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("EntityLayer.Concrete.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Artwork", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Collection", "Collection")
                        .WithMany("Artworks")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ArtworkLayer", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Artwork", "Artwork")
                        .WithMany("ArtworkLayers")
                        .HasForeignKey("ArtworkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.CollectionLayer", "CollectionLayer")
                        .WithMany("ArtworkLayers")
                        .HasForeignKey("CollectionLayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("CollectionLayer");
                });

            modelBuilder.Entity("EntityLayer.Concrete.ArtworkTag", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Artwork", "Artwork")
                        .WithMany("ArtworkTags")
                        .HasForeignKey("ArtworkID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Tag", "Tag")
                        .WithMany("ArtworkTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artwork");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Collection", b =>
                {
                    b.HasOne("EntityLayer.Concrete.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CollectionAnalytic", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Collection", "Collection")
                        .WithMany("CollectionAnalytics")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CollectionLayer", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Collection", "Collection")
                        .WithMany("CollectionLayers")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.LayerType", "LayerType")
                        .WithMany("CollectionLayers")
                        .HasForeignKey("LayerTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("LayerType");
                });

            modelBuilder.Entity("EntityLayer.Concrete.LayerTag", b =>
                {
                    b.HasOne("EntityLayer.Concrete.CollectionLayer", "CollectionLayer")
                        .WithMany()
                        .HasForeignKey("CollectionLayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntityLayer.Concrete.Tag", "Tag")
                        .WithMany("LayerTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CollectionLayer");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("EntityLayer.Concrete.LayerType", b =>
                {
                    b.HasOne("EntityLayer.Concrete.Collection", "Collection")
                        .WithMany("LayerTypes")
                        .HasForeignKey("CollectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Artwork", b =>
                {
                    b.Navigation("ArtworkLayers");

                    b.Navigation("ArtworkTags");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Collection", b =>
                {
                    b.Navigation("Artworks");

                    b.Navigation("CollectionAnalytics");

                    b.Navigation("CollectionLayers");

                    b.Navigation("LayerTypes");
                });

            modelBuilder.Entity("EntityLayer.Concrete.CollectionLayer", b =>
                {
                    b.Navigation("ArtworkLayers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.LayerType", b =>
                {
                    b.Navigation("CollectionLayers");
                });

            modelBuilder.Entity("EntityLayer.Concrete.Tag", b =>
                {
                    b.Navigation("ArtworkTags");

                    b.Navigation("LayerTags");
                });

            modelBuilder.Entity("EntityLayer.Concrete.User", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
